ambiot/ambz2_matter

tools/matter/gen-certs.sh
- Build PAA with custom VID/PID
- Add CD remapping feature to map the vid/pid to end product's vid/pid
- To use CD remapping, comment the "CD without dac_origin_vid, dac_origin_pid section", and then uncomment the "CD with dac_origin_vid, dac_origin_pid section"
=> [Tools] Update gen-certs 

tools/AmebaZ2/Image_Tool_Linux/flash.sh
- Change Ameba_ImageTool and flash.sh file permissions to executable
- Update flash.sh to pass in path to image instead of the path to image directory
- Example usage ./flash.sh "device port" "path to image"
=> [Tools] Fix z2 flash script failing

tools/AmebaZ2/Image_Tool_Linux/flash.sh
When using flashing script to flash image to other address other than the default 0x0800000, image tool will save this new address as the default address.
Need to set it back to 0x08000000 when no address is passed in.
=> [Tools] Flash script should explicitly set 0x08000000

component/common/application/matter/application/matter_utils.h
- Use 602 for certs
- Use 256 for verifier
- Use 68 for all other factorydata
=> [Utils] [FactoryData] Optimize ram usage for factorydata

component/common/api/network/include/lwipopts.h
* Insufficient timeout when attempting to do TCP retry, increase MEMP_NUM_SYS_TIMEOUT
=> [lwip] increase system timeout

project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip.mk, project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip_chef_core.mk, project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip_light_core.mk, project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip_otar_core.mk, project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip_switch_core.mk
- compile error is due to multiple files in matter sdk having the same name `IP.cpp`
- during compilation, all the `.ii` intermediate files will be put into `build/chip`, causing the two files to replace each other
- we don't need to save the `.ii` files when building libCHIP
- remove --save-temps flag to prevent saving `.ii` files
=> [build] fix intermittent compile error when making matter lib

.github/workflows/main.yml
- only checks all-clusters-app and lighting-app build
- this build checks only use default configs
- triggered on PR to main
- time taken to complete ci build: ~30min
=> [ci] ci build checks for all-clusters-app and lighting-app

component/common/application/matter/application/matter_dcts.c, component/common/application/matter/application/matter_dcts.h
Addresses #19 
- stop using hardcoded domains
- create 2 DCT pools, DCT1 and DCT2
- no of DCT1 modules = NUM_MODULES
- no of DCT2 modules = NUM_MODULES2
- DCT1 stores variables <=64B
- DCT2 stores variables >64B
- during getting, loop all modules in DCT1 then DCT2
=> [DCT] Rework DCT

component/common/application/matter/common/port/matter_wifis.h
- define JOIN_HANDSHAKE_DONE
- to check for handshake done before running DHCPProcess in ConnectivityManagerImpl
- fix #45
=> [wifi] extern rtw_join_status for matter sdk to use

MATTER.md, component/common/application/matter/example/light/Makefile, component/common/application/matter/example/light/README.md, component/common/application/matter/example/light/lib_chip_light_core.mk, component/common/application/matter/example/light/lib_chip_light_main.mk, project/realtek_amebaz2_v0_example/GCC-RELEASE/Makefile, project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip.mk, project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip_chef_core.mk, project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip_chef_main.mk, project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip_light_core.mk, project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip_light_main.mk, project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip_main.mk, project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip_otar_core.mk, project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip_otar_main.mk, project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip_switch_core.mk, project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip_switch_main.mk, tools/matter/codegen_helpers/check_zap.sh
- add `check_zap.sh` to install zap under `tools/matter/codegen_helpers/zap`
- make commands will call `check_zap.sh` and then export the zap path to `ZAP_INSTALL_PATH`
- shifted codegen output to matter sdk under application examples
- switch order of make clean (clean main first, then clean core) in order to preserve `cluster-file.txt` to avoid error
=> [build] use zapgen to generate zap files during compilation time

component/common/api/wifi/wifi_conf.c
- fix #57 
- store wifi credentials when `wifi_connect()` is successful
- `kWiFiSSIDKeyName` and `kWiFiCredentialsKeyName` must be exactly the same key as the keys in `src/platform/AmebaUtils.cpp`
=> [wifi] store wifi in dct when wifi_connect() is successful

component/common/bluetooth/realtek/sdk/board/common/src/cycle_queue.c
- MallocCycQueue(), return false when memory alloc fail for cyc_buffer
fix #66
=> [bluetooth] fix potential nullptr dereference

component/common/application/matter/example/light/lib_chip_light_main.mk, project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip_chef_main.mk, project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip_light_main.mk, project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip_main.mk, project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip_otar_main.mk, project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip_switch_main.mk
- matter SHA `d7971c0` removes af-event.[h |cpp] files
- remove af-event.cpp from all app's lib_main files 
- add route hook to all examples
=> [build] remove af-event.cpp from build and add route hook to all examples

component/common/application/matter/core/matter_core.cpp, component/common/application/matter/core/matter_interaction.cpp, component/common/application/matter/example/light/matter_drivers.cpp
- fix compile error when building porting layer light example
- due to update in matter sdk, certain cluster and attribute id files are removed
=> [portinglayer] update the cluster and attribute id filepath

component/common/application/matter/example/light/matter_drivers.cpp, component/common/application/matter/example/thermostat/matter_drivers.cpp
- call `UnlockChipStack` when error occur, else chipstack is locked forever
- cleanups
- Fix #80
=> [portinglayer] fix unlock bug

component/common/application/matter/common/port/matter_dcts.c
- add 4 to `VARIABLE_VALUE_SIZE` and `VARIABLE_VALUE_SIZE2`
- else, the max variable size is 60 and 396 respectively
=> [dct] plus 4 to variable size

component/common/application/matter/common/mbedtls/mbedtls_config.h, component/common/network/ssl/mbedtls-matter/include/mbedtls/aes.h, component/common/network/ssl/mbedtls-matter/library/aes.c, component/common/network/ssl/mbedtls-matter/library/platform.c, component/common/network/ssl/ssl_func_stubs/rom/rom_ssl_func_stubs.h, component/common/network/ssl/ssl_func_stubs/ssl_func_stubs.c, project/realtek_amebaz2_v0_example/GCC-RELEASE/application.is.matter.mk
- HW crypto supported by z2: AES CBC and ECB mode
- `mbedtls_aes_setkey_enc`, `mbedtls_aes_setkey_dec`, `mbedtls_aes_crypt_ebc`, `mbedtls_aes_crypt_cbc`
- remove DES, no longer supported on z2
- to enable HW crypto, enable `RTL_HW_CRYPTO` in `mbedtls_config.h` (enabled by default)
=> [mbedtls] hw crypto support on mbedtls 2.28

component/common/application/matter/common/port/matter_utils.c
- check if factorydata length is more than 2048
- if it is more than 2048, this means factorydata is not flashed
- NOR flash default value is 0xffff, which might cause it to read 0xffff length of data
- return to prevent reading from non-existent address
=> [factorydata] return error when factorydata length is more than 2kb

project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip.mk
- fallback to use this if reading factorydata fails
=> [factorydata] enable transitional commissionabledataprovider

component/common/api/wifi/wifi_conf.c, component/common/application/matter/common/port/matter_wifis.c, component/common/application/matter/common/port/matter_wifis.h
- wifi info will be stored upon successful commissioning, handled by matter code
- add new API for matter to get wifi ssid and password
- fix #91
=> [wifi] remove storing wifi into dct during wifi_connect

project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip_chef_core.mk, project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip_light_core.mk, project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip_otar_core.mk, project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip_switch_core.mk
- use transitional commissionabledataprovider for fallback if read factorydata fails
=> [factorydata] enable transitional commissionabledataprovider for all examples

component/common/application/matter/common/port/matter_wifis.c, component/common/application/matter/common/port/matter_wifis.h
- during wifi scan, instead of memcpying the matter_userdata into the pointer passed in, just return matter_userdata
=> [wifi] return pointer to matter_userdata

component/common/application/matter/example/light/example_matter_light.cpp, component/common/application/matter/example/light/matter_drivers.cpp, component/common/application/matter/example/light/matter_drivers.h
- without this, the chip-tool will return INVALID_COMMAND when running `chip-tool identify trigger-effect 0 0 1 1`
- this adds the identify cluster on ep1 and also add some handlers for stop, start and triggereffect
=> [portinglayer] add identify cluster on endpoint 1

component/common/application/matter/common/port/matter_utils.c
- change the length limit to 4096, makes more sense since we put it to the last 4KB of flash
- also give some buffer space for the future should matter/customer require more data to be stored in factory data
=> [factorydata] change factorydata length check limit to 4096

project/realtek_amebaz2_v0_example/GCC-RELEASE/Makefile
- fix #97 
- don't waste time regenerating files from zap if zap didn't change
=> [build] don't regenerate cluster files if zap didn't change

component/common/application/matter/common/port/matter_timers.h, component/common/application/matter/example/light/lib_chip_light_main.mk, component/common/application/matter/example/thermostat/lib_chip_thermostat_main.mk, project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip_chef_main.mk, project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip_light_main.mk, project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip_main.mk, project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip_otar_main.mk, project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip_switch_main.mk
- due to the pigweed repo update (https://github.com/project-chip/connectedhomeip/commit/6025455464090462cd0f97e15d0bc383f115553c)
- the build will fail with following issues
1. Need to include `<ctime>` or `<timer.h>` in `matter_timers.h`
2. Intermediate files (i and s) won't be generated in `GCC-RELEASE`, cp the intermediate files with `lib_main` suffix to info dir
=> [build] fix build after pigweed update

component/common/application/matter/core/matter_core.cpp, component/common/application/matter/example/light/Makefile, component/common/application/matter/example/thermostat/Makefile
- launch matter shell and binding if enabled
- route hook initialize only during kIpV6_Assigned
- new event for commissioning complete, store provisioned wifi info after receiving this event
- update factorydata init sequence
- also update the portinglayer example makefiles so dont need to regen zap genfiles when zap didnt change
=> [portinglayer] update init sequence in matter_core

component/common/application/matter/common/atcmd/atcmd_matter.c
- fix #26 
- use atcmd for matter shell commands
- matter atcmd starts with `ATM` prefix
- eg usage for matter shell commands: 
- `ATMS=help`
- `ATMS=device factoryreset`
=> [shell] matter shell using loguart support

component/common/application/matter/common/mbedtls/mbedtls_config.h
* Enable SUPPORT_HW_SW_CRYPTO to avoid mbedtls error when use_hw_crypto_func is set to 0
Notes:
* On default define both RTL_HW_CRYPTO and SUPPORT_HW_SW_CRYPTO, and will use HW crypto (rom_ssl_ram_map.use_hw_crypto_func = 1)
* Customer can decide to use HW or SW crypto by setting rom_ssl_ram_map.use_hw_crypto_func in platform_set_malloc_free()
=> [mbedtls] fix mbedtls error when hw crypto is disabled

component/common/application/matter/common/bluetooth/matter_blemgr_common.c, component/common/application/matter/common/bluetooth/matter_blemgr_common.h, component/common/bluetooth/realtek/sdk/example/ble_matter_adapter/ble_matter_adapter_app.c, component/common/bluetooth/realtek/sdk/example/ble_matter_adapter/ble_matter_adapter_app.h, component/common/bluetooth/realtek/sdk/example/ble_matter_adapter/ble_matter_adapter_app_flags.h, component/common/bluetooth/realtek/sdk/example/ble_matter_adapter/ble_matter_adapter_app_main.c, component/common/bluetooth/realtek/sdk/example/ble_matter_adapter/ble_matter_adapter_app_main.h, component/common/bluetooth/realtek/sdk/example/ble_matter_adapter/ble_matter_adapter_app_task.c, component/common/bluetooth/realtek/sdk/example/ble_matter_adapter/ble_matter_adapter_app_task.h, component/common/bluetooth/realtek/sdk/example/ble_matter_adapter/ble_matter_adapter_service.c, component/common/bluetooth/realtek/sdk/example/ble_matter_adapter/ble_matter_adapter_service.h, component/common/bluetooth/realtek/sdk/example/bt_mesh_multiple_profile/bt_mesh_device_matter/bt_mesh_device_matter_app_task.c, project/realtek_amebaz2_v0_example/GCC-RELEASE/application.is.matter.mk, project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip.mk, project/realtek_amebaz2_v0_example/inc/platform_opts_bt.h
- Add ble_matter_adapter that uses one shot adv to support multiple adv ability.
- To enable ble_matter_adapter with multiple adv function:
Enable CONFIG_MATTER_BLEMGR_ADAPTER in lib_chip.mk
Enable BLE_MATTER_ADAPTER in application.is.matter.mk
** To support 2 ble slave connection feature, needs to update bt_normal_patch.c based on customer specific needs.
=> [ble] Add ble_matter_adapter and support multiple adv

component/common/application/matter/core/matter_interaction.cpp, component/common/application/matter/example/light/example_matter_light.cpp, component/common/application/matter/example/thermostat/example_matter_thermostat.cpp
- fix #123 
- the `example_matter_xxx_task` is only for starting up the matter related tasks, once it has done its job, we need to delete it, else the idle task cannot run and do cleanup
- in `uplink` and `downlink` tasks, let them block while waiting for event to arrive on the queue
=> [portinglayer] fix tasks hogging the cpu

component/common/application/matter/core/matter_events.h, component/common/application/matter/core/matter_interaction.cpp
- set maximum size of data to be 256 for string values
- the increase in ram usage is not a problem as the event will be cleared after `xQueueReceive` successfully received and handled the data
=> [portinglayer] add a str field in the union for string data

component/common/application/matter/common/port/chip_porting.h, component/common/application/matter/common/port/matter_dcts.c, component/common/application/matter/common/port/matter_dcts.h, component/common/application/matter/common/port/matter_timers.c, component/common/application/matter/common/port/matter_timers.h, component/common/application/matter/common/port/matter_utils.c, component/common/application/matter/common/port/matter_wifis.c, component/common/application/matter/common/port/matter_wifis.h, component/common/application/matter/example/light/lib_chip_light_main.mk, component/common/application/matter/example/thermostat/lib_chip_thermostat_main.mk, project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip_light_main.mk, project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip_main.mk, project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip_otar_main.mk, project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip_switch_main.mk
- Standardize return types for below api
- wifi
- dct
- flash
- The real mapping happens inside AmebaUtils in matter sdk
- Added timer related api
- Added more wifi related api
- run dhcp for both ipv4 and ipv6
- matter will call release ip api on disconnect
- add AclStorage and DefaultAclStorage
=> [portinglayer] Implement error mapping support for matter sdk

component/common/api/at_cmd/atcmd_wifi.c
* Fix softap unable to start in WEP/WPA/WPA2/WPA3 and others that sets password
* Synchronize with https://github.com/ambiot/ambz2_sdk/commit/84f29db3db1da3b834197d0c12212ac9aef42e7b
=> [SDK] fix softap start fail

component/common/application/matter/example/aircon/lib_chip_aircon_core.mk, component/common/application/matter/example/aircon/lib_chip_aircon_main.mk, component/common/application/matter/example/light/lib_chip_light_core.mk, component/common/application/matter/example/light/lib_chip_light_main.mk, component/common/application/matter/example/thermostat/lib_chip_thermostat_core.mk, component/common/application/matter/example/thermostat/lib_chip_thermostat_main.mk, component/soc/realtek/8710c/cmsis/rtl8710c/include/core_tm9_cache.h, project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip.mk, project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip_chef_core.mk, project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip_chef_main.mk, project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip_light_core.mk, project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip_light_main.mk, project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip_main.mk, project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip_otar_core.mk, project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip_otar_main.mk, project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip_switch_core.mk, project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip_switch_main.mk
- matter sdk update requires to use C++17
- remove old `register` keywords
- remove `error-mapping` from build
=> [build] update build to use gnu++17

project/realtek_amebaz2_v0_example/GCC-RELEASE/application.is.matter.mk, project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip_main.mk
- fix weak callbacks not being overriden by adding the `whole-archive` linker flag
- add all-clusters delegates for new device types
=> [build] V1.2 te2 fixes

component/common/application/matter/core/matter_data_model.cpp, component/common/application/matter/example/light_dm/example_matter_light.cpp, component/common/application/matter/example/light_dm/lib_chip_light_core.mk, component/common/application/matter/example/light_dm/lib_chip_light_main.mk, component/common/application/matter/example/light_dm/matter_drivers.cpp, component/common/application/matter/example/light_dm/matter_drivers.h
Restyled the pointer and reference declarations at matter_data_model.cpp, example_matter_light.cpp, matter_drivers.cpp, matter_drivers.h, and deleted some commented out commands at lib_chip_light_core.mk, and lib_chip_light_main.mk
=> Restyle the previous matter-data-model branch

component/common/application/matter/core/matter_data_model.h, component/common/application/matter/core/matter_data_model_presets.cpp
- nullptr memcpy for CHAR_STRING data types, add checks for nullptr first
- add basicinfoCapabilityMinima to basicinfo cluster
=> [portinglayer] fixes for datamodel

tools/matter/factorydata/gen-certs-enhanced.sh
* Do not remove default gen-certs.sh as there are customer still using it.
* Enhanced version has added more arguments for vid, pid, existing paa_cert, existing paa_key, endproduct_vid and endproduct_pid
* Allows user to decide if PAI is vid-scoped, and how many DAC(s) should be generated
* Changed certification_type to 1
* resolves #25
=> [tools] add enhanced version of gen-certs.sh

component/common/application/matter/common/atcmd/atcmd_matter.c
Fix #69 and Fix #128 
- added wifi_disconnect() to disconnect from the current connected wifi.
- added sys_reset() to directly reboot the board after factory reset.
=> [ble-wifi] update factory reset to disconnect wifi and reset the board

component/common/application/matter/core/matter_core.cpp
changed '#include <support/ErrorStr.h>' to '#include <core/ErrorStr.h>' because the file in the connectedhomeip repository was moved
=> [portinglayer] Fix include header

component/common/api/at_cmd/atcmd_lwip.c, component/common/api/at_cmd/atcmd_wifi.c, component/common/api/network/src/ping_test.c, component/common/api/wifi/wifi_conf.c, component/common/application/matter/common/port/matter_wifis.c, component/common/application/matter/example/aircon/example_matter_aircon.cpp, component/common/application/matter/example/chiptest/example_matter.c, component/common/application/matter/example/light/example_matter_light.cpp, component/common/application/matter/example/thermostat/example_matter_thermostat.cpp, component/common/example/example_entry.c, component/common/example/httpd/readme.txt, component/common/example/socket_tcp_trx/example_socket_tcp_trx_1.c, component/common/example/socket_tcp_trx/example_socket_tcp_trx_2.c, component/common/example/ssl_server/readme.txt, component/common/example/wlan_fast_connect/example_wlan_fast_connect.c, project/realtek_amebaz2_v0_example/GCC-RELEASE/application.is.matter.mk, project/realtek_amebaz2_v0_example/example_sources/pm_sleepcg/src/main.c, project/realtek_amebaz2_v0_example/example_sources/pwm-buzzer/src/main.c, project/realtek_amebaz2_v0_example/example_sources/pwm/src/main.c, project/realtek_amebaz2_v0_example/inc/platform_opts.h
These changes is to fix issues was found during sdk quality check:
* fix compile error due to lwip_v2.1.2 when enabling CONFIG_EXAMPLE_UART_ATCMD
* fix spelling error when printing wifi scan result for WPA3
* fix compile error after enabling CONFIG_BT_CONFIG, CONFIG_BT_AIRSYNC_CONFIG, CONFIG_BT_SCATTERNET, CONFIG_BT_BEACON and CONFIG_BT_FUZZ_TEST
* fix heap leakage when performing ping_test continuously
* fix build error when disabling LWIP_IPV6
* Correct cJSON header path
* Modify readme to change mbedtls configuration for matter
* fix tcp example hardfault due stack overflow after enabling LWIP_TCPIP_CORE_LOCKING
* fix ota example hardfault due to not using the same flash layout defined in platform_opts.h
* fix peripheral example
* Support wpa/wpa2/wpa3 and other encryption type for …
=> [sdk] fix several issues

project/realtek_amebaz2_v0_example/GCC-RELEASE/Makefile, project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip_air_purifier_core.mk, project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip_air_purifier_main.mk
=> [sdk] add air purifier example

component/common/application/matter/example/aircon/lib_chip_aircon_main.mk, component/common/application/matter/example/bridge_dm/lib_chip_bridge_main.mk, component/common/application/matter/example/dishwasher/lib_chip_dishwasher_main.mk, component/common/application/matter/example/laundrywasher/lib_chip_laundrywasher_main.mk, component/common/application/matter/example/light/lib_chip_light_main.mk, component/common/application/matter/example/light_dm/lib_chip_light_main.mk, component/common/application/matter/example/refrigerator/lib_chip_refrigerator_main.mk, component/common/application/matter/example/thermostat/lib_chip_thermostat_main.mk, component/common/drivers/wlan/realtek/src/core/option/rtw_opt_skbuf.c, project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip_air_purifier_main.mk, project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip_chef_main.mk, project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip_light_main.mk, project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip_main.mk, project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip_otar_main.mk, project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip_switch_main.mk
* Synchronized code with internal git to match lib_wlan.a and do alignment for buffer
* Fix build error due to SHA:54c97231c6fcb791da35e59944c227db3e2d5c2b, where attribute-size-util.cpp has been removed
=> [sdk] fix spic error when using rtw_opt_skbuf.c

component/common/application/matter/common/port/matter_dcts.c, component/common/application/matter/common/port/matter_utils.c
* mbedtls_aes_crypt_ctr returns 0 and DecodeFactoryData remaps 0 as CHIP_ERROR_INTERAL causing failure in factorydata
* Fix return values not handled when factorydata or dct ecnryption is enabled
=> [sdk] fix factorydata encryption and dct encryption bug

component/common/application/matter/common/port/chip_porting.h, component/common/application/matter/common/port/matter_wifis.c, component/common/application/matter/common/port/matter_wifis.h
- Added matter API for lwip and wifi functions in matter_wifis.c/h including:
- matter_LwIP_GetIPv6_linklocal
- matter_LwIP_GetIPv6_global
- matter_LwIP_GetIP
- matter_LwIP_GetGW
- matter_LwIP_GetMASK
- matter_wifi_get_setting
- matter_wifi_reg_event_handler
- Modified matter API arguments for wifi functions in matter_wifis.c/h including:
- matter_wifi_get_security_type
- matter_wifi_get_wifi_channel_number
- Included wifi_structures.h in chip_porting.h
=> [wifi] Matter API Update

component/common/application/matter/example/aircon/lib_chip_aircon_main.mk, component/common/application/matter/example/bridge_dm/lib_chip_bridge_main.mk, component/common/application/matter/example/dishwasher/lib_chip_dishwasher_main.mk, component/common/application/matter/example/fan/lib_chip_fan_main.mk, component/common/application/matter/example/laundrywasher/lib_chip_laundrywasher_main.mk, component/common/application/matter/example/light/lib_chip_light_main.mk, component/common/application/matter/example/light_dm/lib_chip_light_main.mk, component/common/application/matter/example/refrigerator/lib_chip_refrigerator_main.mk, component/common/application/matter/example/thermostat/lib_chip_thermostat_main.mk, project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip_air_purifier_main.mk, project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip_chef_main.mk, project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip_light_main.mk, project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip_main.mk, project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip_otar_main.mk, project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip_switch_main.mk, tools/matter/codegen_helpers/expected.outputs
* all-clusters-app/ameba operation state has been moved to all-clusters-app/all-clusters-common/src, therefore adding files to fix missing definition.
* add app/cluster-init-callback.cpp for cluster initialization
=> [sdk] fix build issue with operational state

component/common/api/lwip_netconf.c
* Fix long commissioning time
Notes:
* After DHCP, Commissioner will send BLE indication packet, and at the same time, DHCP6 is on-going, if DHCP6 takes a long time, BLE seems to take over the task and repeatly communicating, despite wifi started dnssd.
* To prevent this issue, when DHCP6 starts, if IPv6 address is valid, trigger DHCP6 event and allow dnssd to start first before BLE communication.
=> [wifi] fix long commissioning time

component/common/application/matter/example/aircon/lib_chip_aircon_main.mk, component/common/application/matter/example/bridge_dm/lib_chip_bridge_main.mk, component/common/application/matter/example/dishwasher/lib_chip_dishwasher_main.mk, component/common/application/matter/example/fan/lib_chip_fan_main.mk, component/common/application/matter/example/laundrywasher/lib_chip_laundrywasher_main.mk, component/common/application/matter/example/light/lib_chip_light_main.mk, component/common/application/matter/example/light_dm/lib_chip_light_main.mk, component/common/application/matter/example/refrigerator/lib_chip_refrigerator_main.mk, component/common/application/matter/example/thermostat/lib_chip_thermostat_main.mk, project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip_air_purifier_main.mk, project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip_chef_main.mk, project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip_light_main.mk, project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip_main.mk, project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip_otar_main.mk, project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip_switch_main.mk
* MatterReportingAttributeChangeCallback was removed from ember-compatibility-functions.cpp and added into reporting.cpp in SHA:d338455 of connectedhomeip
=> [build] fix build issue with MatterReportingAttributeChangeCallback

component/common/api/wifi/wifi_conf.c
* Remove unregistering of wifi event as it will affect next retry connection by driver.
Notes:
* When driver retries, it does not enter from wifi_connect again, so wifi event will not be re-registered if un-registered in wifi_disconn_hdl. This will cause the next connection to timeout as Semaphore is unable to release
=> [wifi] remove unregister of wifi event

component/common/application/matter/common/port/matter_timers.c, component/common/application/matter/common/port/matter_timers.h, component/common/application/matter/core/matter_core.cpp, component/common/application/matter/core/matter_events.h, component/common/application/matter/driver/dishwasher_mode.h, component/common/application/matter/driver/fan_driver.h, component/common/application/matter/driver/tcc_mode.h, component/common/application/matter/example/chiptest/example_matter.c
* Add system time wrapper
* Use gtimer instead of freertos time as freertos only covers until 32-bits, but matter requires 64-bits
* Fix build issue with af.h as header has been removed and declaration is moved to attribute-table.h
=> Update system time

component/common/application/matter/driver/dishwasher_driver.cpp, component/common/application/matter/driver/fan_driver.cpp, component/common/application/matter/driver/led_driver.cpp, component/common/application/matter/driver/washer_driver.cpp, component/common/mbed/hal/pwmout_api.h
* As pwmout_period_us and hal_pwm_enable has been removed in pwmout_init, it requires calling pwmout_period_us and pwmout_start in application to successfully start pwm
=> [sdk] fix pwm unable to start

component/common/application/matter/common/atcmd/atcmd_matter.c, component/common/application/matter/common/port/matter_fs.c, component/common/application/matter/common/port/matter_fs.h, component/common/application/matter/driver/diagnostic_logs/ameba_diagnosticlogs_provider_delegate_impl.cpp, component/common/application/matter/driver/diagnostic_logs/ameba_logging_faultlog.cpp, component/common/application/matter/driver/diagnostic_logs/ameba_logging_insert_logs.cpp, component/common/application/matter/driver/diagnostic_logs/ameba_logging_insert_logs.h, component/common/application/matter/example/aircon/lib_chip_aircon_main.mk, component/common/application/matter/example/bridge_dm/lib_chip_bridge_main.mk, component/common/application/matter/example/dishwasher/lib_chip_dishwasher_main.mk, component/common/application/matter/example/fan/lib_chip_fan_main.mk, component/common/application/matter/example/laundrywasher/lib_chip_laundrywasher_main.mk, component/common/application/matter/example/light/lib_chip_light_main.mk, component/common/application/matter/example/light_dm/lib_chip_light_main.mk, component/common/application/matter/example/refrigerator/lib_chip_refrigerator_main.mk, component/common/application/matter/example/thermostat/lib_chip_thermostat_main.mk, project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip_air_purifier_main.mk, project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip_chef_main.mk, project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip_light_main.mk, project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip_main.mk, project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip_otar_main.mk, project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip_switch_main.mk
* fix failure when testing TC-DLOG-2.1
Notes:
* Failed to erase data from file system, so must remove when EndLogCollection is called
* Failed to trigger Success (status=0), have to insert data first
* Failed to trigger Exhaust (status=1), have to insert data which is less than 1024
* Added ATcmd for inserting logs: 
-. $$$$=1025 (or above) to get user log with status = 0 
-. $$$$=1024 (or below) to get user log with status = 1 
-. ^^^^=1025 (or above) to get network log with status = 0 
-. ^^^^=1024 (or below) to get network log with status = 1 
-. #### to get crash log with status = 0 
-. @@@@ to get crash log with status = 1 
-. Don't insert any logs to get status = 2
=> [sdk] fix diagnostic logs cluster
