ambiot/ambz2_matter

component/common/application/matter/common/bluetooth/bt_matter_adapter/bt_matter_adapter_service.c
component/common/application/matter/common/bluetooth/bt_matter_adapter/bt_matter_adapter_service.h

- Align with matter specs to use indicate

[BLE] Replace notify with indicate

---

project/realtek_amebaz2_v0_example/GCC-RELEASE/application.is.matter.mk

* fix build error due to missing header files of mbedtls when make is_matter

[mbed] fix mbedtls build error

---

tools/matter/factorydata/gen-certs.sh

* On default use gen-cert.sh without dac origin

[Tools] update gen cert

---

doc/matter/FactoryData_guide.md

[Readme] Add guide for FactoryData

---

project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip_chef_main.mk
project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip_light_main.mk
project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip_main.mk
project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip_otar_main.mk
project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip_switch_main.mk

- `ClientMonitoringRegistrationTable` has been merged to matter sdk upstream
- added the src file to build pass

[build] add ClientMonitoringRegistrationTable

---

tools/matter/codegen_helpers/check_zap.sh

[tools] update zap version

---

component/common/application/matter/common/port/matter_wifis.c
component/common/application/matter/common/port/matter_wifis.h

* Add wrapper function for matter to call function in ameba
* Support Open Security and WEP Security Mode
* Fix #43

[wifi] Rework matter wifi api

---

tools/matter/codegen_helpers/check_zap.sh

- update zap to v2023.01.31-nightly

[tools] zap update to v2023.01.31-nightly

---

component/os/os_dep/device_lock.c

- free mutex when DEVICE_MUTEX_IS_INIT
fix #65

[os] fix device_mutex_free_logic

---

component/common/application/matter/common/interface/matter_interface.cpp
component/common/application/matter/common/interface/matter_interface.h
component/common/application/matter/example/light/lib_chip_light_main.mk

- interface to get matter status
- only able to call when using the porting layer
- currently added API to get matter commissioning status
- to add more API in the future, please also suggest what API to add

[portinglayer] add interface to get status from matter

---

component/common/application/matter/example/light/Makefile
component/common/application/matter/example/thermostat/Makefile
project/realtek_amebaz2_v0_example/GCC-RELEASE/Makefile

- zap-template file name change
- https://github.com/project-chip/connectedhomeip/pull/26617

[build] update zap-template file

---

component/common/application/matter/example/light/Makefile
component/common/application/matter/example/thermostat/Makefile
project/realtek_amebaz2_v0_example/GCC-RELEASE/Makefile

- This reverts commit 31eb0e8e6b6a0ecae753f4bc40d4357541bf31a4.
- Above commit should be merged after `v1.1.0.1` tag.

Revert "[build] update zap-template file (#115)"

---

component/common/application/matter/example/light/Makefile
component/common/application/matter/example/thermostat/Makefile
project/realtek_amebaz2_v0_example/GCC-RELEASE/Makefile

* Re-application of commit 31eb0e8e6b6a0ecae753f4bc40d4357541bf31a4
* [build] update zap-template file
* portinglayer zap-template update

Re-apply [build] update zap-template file (#115)

---

component/common/application/matter/common/port/matter_dcts.c

- return after deleting the key successfully

Deletekey bug

---

component/common/bluetooth/realtek/sdk/example/ble_central/ble_central_at_cmd.c

* Fix DUT show no respond when trying to connect to SUT
JIRA: https://jira.realtek.com/browse/RTSSQC-1738
Synchronize from https://github.com/ambiot/ambz2_sdk/commit/1b639fa273cdb82423cf3856e5ccef91778c01da

[ble] fix bt central connect peripheral fail

---

.github/workflows/main.yml

- ci is failing because of not enough space
- add action to free space by deleting useless stuff

[ci] free space for ci

---

component/common/application/matter/example/aircon/lib_chip_aircon_main.mk
component/common/application/matter/example/light/lib_chip_light_main.mk
component/common/application/matter/example/thermostat/lib_chip_thermostat_main.mk
project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip_chef_main.mk
project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip_light_main.mk
project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip_main.mk
project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip_otar_main.mk
project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip_switch_main.mk

- move icd to different folder
- add smoke and temp level for all-clusters-app

[build] add smokeco, temp_level and move icd

---

component/common/application/matter/example/aircon/lib_chip_aircon_main.mk
component/common/application/matter/example/light/lib_chip_light_main.mk
component/common/application/matter/example/thermostat/lib_chip_thermostat_main.mk
project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip_chef_main.mk
project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip_light_main.mk
project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip_main.mk
project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip_otar_main.mk
project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip_switch_main.mk

- add `IcdManagementServer.cpp` to build to fix compile errors

[build] add IcdManagementServer

---

component/common/application/matter/example/thermostat/matter_drivers.cpp
component/common/application/matter/example/thermostat/matter_drivers.h

- add identify callbacks for thermostat

[portinglayer] add idenfity callbacks for thermostat

---

.github/workflows/main.yml

[ci] set large-packages to false to workaround fetch fail error

---

component/common/application/matter/example/aircon/lib_chip_aircon_core.mk
component/common/application/matter/example/light/lib_chip_light_core.mk
component/common/application/matter/example/thermostat/lib_chip_thermostat_core.mk
project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip.mk
project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip_chef_core.mk
project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip_light_core.mk
project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip_otar_core.mk
project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip_switch_core.mk

* Add chip_logging option into makefile. This allows user to enable or disable matter logging.
* On default disable chip_detail_logging

[build] add logging option

---

component/common/application/matter/example/light_dm/example_matter_light.cpp

Fix #159 : Added uplink and downlink task to light_dm, referred the fix from [this AmebaD Matter commit](https://github.com/ambiot/ambd_matter/commit/20ac54879a097b82b2575c16a2cae5d841c6de8c)

Added uplink and downlink task to light_dm

---

component/common/application/matter/example/aircon/lib_chip_aircon_main.mk
component/common/application/matter/example/laundrywasher/lib_chip_laundrywasher_main.mk
component/common/application/matter/example/light/lib_chip_light_main.mk
component/common/application/matter/example/light_dm/lib_chip_light_main.mk
component/common/application/matter/example/thermostat/lib_chip_thermostat_main.mk
project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip_chef_main.mk
project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip_light_main.mk
project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip_main.mk
project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip_otar_main.mk
project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip_switch_main.mk

- File name changed in connectedhomeip repository
- Updated IcdManagementServer.cpp to ICDManagementServer.cpp
- Updated IcdMonitoringTable.cpp to ICDMonitoringTable.cpp

[build] Updated Icd to ICD

---

component/common/application/matter/example/aircon/lib_chip_aircon_main.mk
component/common/application/matter/example/laundrywasher/lib_chip_laundrywasher_main.mk
component/common/application/matter/example/light/lib_chip_light_main.mk
component/common/application/matter/example/light_dm/lib_chip_light_main.mk
component/common/application/matter/example/refrigerator/lib_chip_refrigerator_main.mk
component/common/application/matter/example/thermostat/lib_chip_thermostat_main.mk
project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip_chef_main.mk
project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip_light_main.mk
project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip_main.mk
project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip_otar_main.mk
project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip_switch_main.mk

- Exclude Ameba Matter OTA Initializer cpp file when chip_enable_ota_requestor is set to false

[build] Fix Enable OTA Requestor

---

.github/README.md

* Change github README.md to MATTER.md

[sdk] change readme

---

component/common/application/matter/driver/fan_driver.cpp
component/common/application/matter/driver/fan_driver.h
component/common/application/matter/example/aircon/lib_chip_aircon_main.mk
component/common/application/matter/example/aircon/matter_drivers.cpp

* Change FanModeType to FanModeEnum
* Add ACL into aircon makefile

[portinglayer] fix aircon build error

---

component/common/application/matter/example/aircon/lib_chip_aircon_main.mk
component/common/application/matter/example/bridge_dm/lib_chip_bridge_main.mk
component/common/application/matter/example/dishwasher/lib_chip_dishwasher_main.mk
component/common/application/matter/example/fan/lib_chip_fan_main.mk
component/common/application/matter/example/laundrywasher/lib_chip_laundrywasher_main.mk
component/common/application/matter/example/light/lib_chip_light_main.mk
component/common/application/matter/example/light_dm/lib_chip_light_main.mk
component/common/application/matter/example/refrigerator/lib_chip_refrigerator_main.mk
component/common/application/matter/example/thermostat/lib_chip_thermostat_main.mk
project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip_air_purifier_main.mk
project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip_chef_main.mk
project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip_light_main.mk
project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip_main.mk
project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip_otar_main.mk
project/realtek_amebaz2_v0_example/GCC-RELEASE/lib_chip_switch_main.mk

* ICDManagementServer has been removed in SHA:6778d3e5088fb535238c5448889a47b0bf8db2d2

[sdk] fix build error with ICDManagementServer

---

component/common/network/ssl/mbedtls-matter/library/ctr_drbg.c

* Fix build error due to missing semicolon
* Add mutex lock when using crypto

[mbedtls] fix matter prng

---

MATTER.md

* Add reminder for the location change of all-clusters-app.zap

[sdk] update matter readme

---

doc/matter/FactoryData_guide.md
tools/matter/factorydata/ameba_factory_window.py

* Add factorydata support for Window OS

[tools] support factorydata generator in window

---

tools/matter/qrcode/Base38.py
tools/matter/qrcode/README.md
tools/matter/qrcode/generate_setup_payload.py

* Support QR Code generator in window

Qr code tool

---

project/realtek_amebaz2_v0_example/GCC-RELEASE/Makefile

* Remove unnecessary make command

[sdk] update makefile

---

component/common/application/matter/project/amebaz2/Makefile
project/realtek_amebaz2_v0_example/GCC-RELEASE/Makefile

* add toolchain_matter to prevent conflicts with default

[sdk] matter restructure part 3
